### ISSUE TITLE
Support older versions of php

### ISSUE THREAD

**Issue by ashalan** [tonystar/drupal-domain-path-rewrite#2]
Getting errors:
Parse error: syntax error, unexpected '[' in /sites/all/modules/contrib/domain_path_rewrite/domain_path_rewrite.module on line 21

**Comment by ashalan** [comment]
This patch should do it:

'''
diff --git a/domain_path_rewrite.module b/domain_path_rewrite.module
index ac798af..c1ef06d 100644
--- a/domain_path_rewrite.module
+++ b/domain_path_rewrite.module
@@ -18,7 +18,16 @@ function domain_path_rewrite_init() {
  */
 function domain_path_rewrite_url_inbound_alter(&$path, $original_path, $path_language) {
   global $_domain;
-  $domain_key = empty($_domain['machine_name']) ? domain_load($_domain['domain_id'])['machine_name'] : $_domain['machine_name'];
+  
+  $domain_key = '';
+
+  if (empty($_domain['machine_name'])) {
+    $load = domain_load($_domain['domain_id']);
+    $domain_key = $load['machine_name'];
+  }
+  else {
+    $domain_key = $_domain['machine_name'];
+  } 
   $redirect_source = $domain_key . ':' . ($original_path ? $original_path : '<front>');
 
   if (module_exists('redirect') && redirect_load_by_source($redirect_source)) {
'''

**Comment by tonystar** [comment]
Fixed in 7.x-1.0-alpha3. Thanks @ashalan!
